import React, { createContext, useState, useContext, useEffect } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => useContext(LanguageContext);

const translations = {
  en: {
    appName: "AGRO-LINK",
    tagline: "AI-Powered Smart Agriculture Marketplace",
    navHome: "Dashboard",
    navMarketplace: "Marketplace",
    navAiHub: "AI Hub",
    navChat: "Bids & Chat",
    navLogout: "Logout",
    
    // Auth Pages
    authTitle: "Welcome to AGRO-LINK",
    authLogin: "Login",
    authRegister: "Register",
    authRole: "Select Your Role",
    roleFarmer: "Farmer (Produce Seller)",
    roleDealer: "Dealer (Crop Buyer)",
    roleShopkeeper: "Shopkeeper (Fertilizer Seller)",
    authEmail: "Email Address",
    authPassword: "Password",
    authName: "Full Name",
    authPhone: "Phone Number",
    authAddress: "Farm/Shop Address",
    authNoAccount: "Don't have an account?",
    authHaveAccount: "Already have an account?",
    authSuccess: "Authenticated successfully!",
    authError: "Authentication failed. Please try again.",

    // Dashboard
    dashTitle: "Agricultural Intelligence Dashboard",
    iotHeader: "IoT Soil Monitoring",
    moisture: "Soil Moisture",
    temperature: "Temperature",
    soilPh: "Soil pH",
    iotAlertOk: "Soil health is optimal",
    iotAlertDanger: "ALERT: Moisture below threshold! Irrigation recommended.",
    weatherHeader: "Real-time Weather & Advisory",
    weatherHumidity: "Humidity",
    weatherWind: "Wind Speed",
    weatherAdvisory: "Agricultural Advisory",
    weatherAdviseFine: "Clear sky. Excellent conditions for crop harvesting and fertilizer spraying.",
    weatherAdviseRain: "Rain expected. Postpone fertilizer application. Check field drainage.",
    voiceAssistant: "Voice Assistant Active",
    voiceInstruction: "Speak 'help' to hear commands. Try saying 'go to AI hub', 'check prices', or 'set Hindi'.",

    // Marketplace
    marketTitle: "Decentralized Agriculture Marketplace",
    marketCropCatalog: "Fresh Farmer Produce",
    marketShopCatalog: "Fertilizers & Pesticides Store",
    marketUploadProduce: "Upload Produce Listing",
    marketUploadProduct: "List Fertilizer/Pesticide Product",
    marketCropName: "Crop Name",
    marketCategory: "Category",
    marketQuantity: "Quantity (kg)",
    marketPrice: "Base Price (per kg)",
    marketDesc: "Description & Grade",
    marketUploadBtn: "Upload Listing",
    nearbyShops: "Nearby Recommended Shopkeepers (within 50 km)",
    nearbyDistance: "Distance",
    nearbyBuy: "Visit Shop",
    makeOfferBtn: "Make Offer / Negotiate",
    buyNowBtn: "Buy Directly",
    orderPlaced: "Order request created successfully!",
    aiListingHeader: "AI Auto-Listing Assistant",
    aiListingDesc: "Upload a photo of your harvest. AGRO-LINK AI will auto-detect the crop, quality grade, and recommended price.",
    aiScanning: "AI Scanning Crop Features...",
    aiSuggestedPrice: "Suggested Price",
    aiDetectedGrade: "Grade",
    aiDetectedQuality: "Quality",
    aiVerifiedBadge: "AI Verified",

    // AI Hub
    aiHubTitle: "Smart Agricultural AI Services",
    aiDiseaseDetect: "AI Leaf Disease Detector",
    aiUploadLeaf: "Upload crop leaf photo to identify diseases and get cures.",
    aiDropzone: "Click or drag leaf photo here",
    aiDetecting: "AI is analyzing leaf patterns...",
    aiCure: "Recommended Cures & Medicines",
    aiPricePredict: "Crop Price Trend Predictor",
    aiSelectCrop: "Select Crop Category",
    aiSelectState: "Select State",
    aiPredictBtn: "Predict Price Trend",
    aiPriceResult: "Predicted Price for next month",
    aiTrend: "Market Trend Status",
    aiSoilRecommend: "NPK Smart Soil Advisory",
    aiEnterNutrients: "Enter N-P-K Soil Values (ppm)",
    aiCheckSoil: "Analyze Soil Health",
    aiSoilStatus: "Soil Nutrient Status",
    aiRecommendedFertilizer: "Best Recommended Fertilizer",
    aiSoilDosage: "Target Dosage",

    // Chat / Negotiation
    chatTitle: "Live Bid Negotiation Room",
    chatActiveOffer: "Current Negotiated Price Offered",
    chatAcceptBtn: "Accept Deal",
    chatRejectBtn: "Reject & Reset",
    chatPlaceBid: "Enter Your Negotiation Offer (₹/kg)",
    chatSendBtn: "Send Offer",
    navCopilot: "AI Copilot",
    copilotChatTitle: "AI Farmer Copilot",
    copilotStatusOnline: "Online (Agronomist Expert)",
    copilotPlaceholder: "Ask me anything about crops, soil, water...",
    copilotClearBtn: "Clear Conversation",
    copilotVoiceActive: "Voice active",
    copilotSpeakBtn: "Speak",
    copilotListening: "Listening...",
    copilotToggleSpeech: "Voice Output",
    copilotSuggestLeaves: "Why are my leaves yellow?",
    copilotSuggestFertilizer: "Which fertilizer to use?",
    copilotSuggestWater: "How much water to irrigate?",
    copilotSuggestCrop: "Best crop for next season?",
    copilotSoilMetrics: "Simulate Soil Telemetry Context",
    copilotSoilMetricsDesc: "Feeding live IoT readings to the AI Copilot for personalized solutions",
    copilotMoistureLabel: "Soil Moisture",
    copilotPhLabel: "Soil pH",
    copilotTempLabel: "Temperature",
    copilotTelemetryCheckbox: "Send Telemetry to AI",
    copilotOpenFullPage: "Open Full Page",
    
    // Price Predictor
    navPricePredictor: "Price Predictor",
    pricePredictorTitle: "AI Crop Price Prediction System",
    pricePredictorDesc: "Input your crop details to predict tomorrow's, 3-day, 7-day, and 15-day prices based on machine learning trend models.",
    priceSelectCrop: "Crop Name",
    priceSelectLocation: "Location (State)",
    priceEnterQuantity: "Quantity (in kg)",
    pricePredictSubmit: "Calculate Forecast",
    priceTomorrow: "Tomorrow Price",
    priceThreeDay: "3-Day Price",
    priceSevenDay: "7-Day Price",
    priceFifteenDay: "15-Day Price",
    priceCurrent: "Current Market Price",
    priceRecommendAction: "AI Recommendation",
    priceSavePrediction: "Save This Prediction",
    pricePredictionHistory: "Prediction History",
    priceHistoryDelete: "Delete",
    priceHistoryEmpty: "No saved predictions found.",
    
    // Negotiation Assistant
    navNegotiationAssistant: "Negotiation Assistant",
    negotiationAssistantTitle: "AI Negotiation Assistant",
    negotiationAssistantDesc: "Evaluate dealer bid offers compared to current market values to verify deal fairness, expected profit, risk profiles, and counter-offer targets.",
    negSelectCrop: "Select Crop",
    negOfferedPrice: "Dealer Offered Price (per kg)",
    negMarketPrice: "Current Market Price (per kg)",
    negQuantity: "Crop Quantity (kg)",
    negLocation: "Farm Location (State)",
    negSubmitBtn: "Analyze Offer Fairness",
    negDifference: "Price Difference",
    negExpectedProfit: "Expected Gross Profit",
    negProfitDiff: "Gain/Loss vs Market",
    negRiskLevel: "Risk Rating",
    negFairnessScore: "Fairness Score",
    negNegotiationScore: "Negotiation Leverage",
    negCounterOffer: "Suggested Counter Offer",
    negHistoryEmpty: "No saved negotiation audits found.",
    
    // Buyer Matching
    navBuyerMatching: "Buyer Matcher",
    buyerMatchingTitle: "AI Smart Buyer Matching",
    buyerMatchingDesc: "Automatically identify and rank the top registered dealers for your harvest based on price, distance, trust index, and transactional history.",
    matchEnterQty: "Quantity of Crop (kg)",
    matchSubmitBtn: "Find Best Buyers",
    matchHistoryTitle: "Saved Buyer Matching Snapshots",
    matchHistoryEmpty: "No saved matching snapshots found.",
    matchDealerName: "Dealer Name",
    matchDistance: "Distance",
    matchPrice: "Price Offered",
    matchTrustScore: "Trust Score",
    matchRating: "Rating",
    matchTransactions: "Transactions",
    matchScore: "Match Score",
    bestProfitBadge: "Best Profit",
    fastestSaleBadge: "Fastest Sale",
    connectDealerBtn: "Negotiate Bid",
    saveMatchSnapshot: "Save Matching Snapshot",
    
    // Crop Health
    navCropHealth: "Crop Health",
    cropHealthTitle: "AI Crop Health & Disease Management",
    cropHealthDesc: "Upload a photo of your crop's leaf to get instant diagnostic identification, severity assessment, custom treatment guidelines, chemical inputs recommendation, and shopkeeper pricing indexes.",
    healthAnalyzeBtn: "Analyze Crop Health",
    healthAnalyzing: "AI is diagnosing leaf anomalies...",
    healthReportTitle: "Crop Health Diagnostic Report",
    healthHistoryTitle: "Crop Health Scan History & Trends",
    healthHistoryEmpty: "No previous crop scans found.",
    symptomsLabel: "Symptoms Identified",
    treatmentLabel: "Prescribed Treatments",
    costLabel: "Estimated Treatment Cost",
    fertilizersLabel: "Recommended Fertilizers",
    pesticidesLabel: "Recommended Pesticides",
    nearbyShopsLabel: "Nearby Shops Selling Recommended Products",
    buyNowInputBtn: "Buy Now",
    printReportBtn: "Print Diagnostic Report",
    severityBadge: "Severity",
    confidenceBadge: "Confidence",
    scanDate: "Scan Date",
    totalScans: "Total Scans Run",
    highSeverityAlerts: "High Severity Alerts",
    healthyScansRatio: "Healthy Scans Rate",
    diseaseTrendChart: "Disease Occurrences Distribution",
    severityTrendChart: "Crop Health Severity Timeline",
    weatherAdvisorTitle: "AI Weather Advisor & Advisory",
    weatherAdvisorDesc: "Live Open-Meteo local forecast integrated with AI expert crop scheduling advisory.",
    irrigationAdvisor: "Irrigation Advisory",
    fertilizerAdvisor: "Fertilization Advisory",
    pestAdvisor: "Pest & Pathogen Risk",
    weeklyForecast: "7-Day Weather Forecast",
    weatherCheckHistory: "Weather Check History",
    weatherTempTrend: "Local Temperature Forecast Trends",
    weatherRainTrend: "7-Day Daily Rain Probability Chart",
    weatherCheckBtn: "Refresh Weather Telemetry",
    weatherChecking: "Retrieving live Open-Meteo feeds...",
    navAgentSystem: "Agent System",
    agentSystemTitle: "AI Multi-Agent Agriculture System",
    agentSystemDesc: "Execute 4 specialized AI Agents running sequentially to diagnose disease, forecast pricing, match buyers, and plan freight logistics in a unified automated run.",
    diseaseAgentLabel: "Agent 1: Leaf Pathology Agent",
    marketAgentLabel: "Agent 2: Price Forecasting Agent",
    buyerAgentLabel: "Agent 3: Matchmaking Broker Agent",
    logisticsAgentLabel: "Agent 4: Dispatch Logistics Agent",
    agentRunBtn: "Trigger Agents Pipeline",
    agentRunning: "Orchestrating AI Agents Pipeline...",
    workflowProgress: "Multi-Agent Workflow Progress",
    agentConsoleLogs: "Agent Pipeline Terminal Feed",
    finalReportTitle: "Unified Agriculture Commerce Report",
    netEarningsLabel: "Net Projected Earnings",
    freightCostLabel: "Freight Shipping Cost",
    grossEarningsLabel: "Gross Crop Valuation",
    workflowHistory: "Multi-Agent Execution History",
    fieldHandbookTitle: "Farmer's Field Handbook & Dictionary",
    moistureHandbookTitle: "Soil Moisture (Water Content)",
    moistureHandbookDesc: "Moisture represents the percentage of water content in the soil. Optimal level for standard crops (Wheat, Tomato) is 40-60%. Below 30% triggers a warning, recommending irrigation to prevent crop wilting.",
    phHandbookTitle: "Soil pH (Soil Acidity/Alkalinity)",
    phHandbookDesc: "Soil pH measures the acidity level. Ideal range is 6.0-7.5 (neutral). Extreme values restrict nutrient absorption; apply agricultural lime for acidic soil, or gypsum for alkaline soil.",
    tempHandbookTitle: "Temperature (Crop Heat Index)",
    tempHandbookDesc: "Ideal growth temperature is 25-32°C. Elevated temperature speeds up soil water evaporation, meaning you need to irrigate more frequently.",
    sporeHandbookTitle: "Fungal Spore Risk Index",
    sporeHandbookDesc: "AI correlates humidity and leaf moisture to predict fungal disease risks. Safe: 0-45%. Warning: 45-75% (spray preventative Neem oil). Danger: >75% (spray curative Copper Oxychloride within 24 hours).",
    agentWorkflowGuideTitle: "AGRO-LINK Multi-Agent Alliance Guide",
    agentWorkflowGuideDesc: "This platform orchestrates 4 specialized AI Agents in a sequential loop to automatically manage your harvest listing, price optimization, matching, and logistics.",
    agent1GuideTitle: "Agent 1: Disease Pathology Agent",
    agent1GuideDesc: "Scans uploaded leaf photographs for visual patterns of disease (like Rust or Blight). Estimates infection severity and prescribes exact bio-chemical cures and treatment costs.",
    agent2GuideTitle: "Agent 2: Market Intelligence Agent",
    agent2GuideDesc: "Pulls state-level mandi pricing history and analyzes price trends using statistical models. Recommends whether you should 'Hold' the crop for a higher price or 'Sell' immediately.",
    agent3GuideTitle: "Agent 3: Matchmaking Broker Agent",
    agent3GuideDesc: "Matches your harvest volume with active registered crop dealers. Evaluates dealer bid prices, trust score index, user ratings, and distance to identify your highest-earning dealer.",
    agent4GuideTitle: "Agent 4: Dispatch Logistics Agent",
    agent4GuideDesc: "Calculates the best shipping routes, selects the optimal vehicle type (e.g. mini-truck), estimates transit hours, and computes freight costs, giving you the Net Projected Earnings.",
    navAiCommandCenter: "AI Command Center",
    aiCommandCenterTitle: "AI Command Center & Diagnostic Room",
    aiCommandCenterDesc: "An integrated operations desk where disease classification, pricing Ridge regressions, nearest dealer bidding profiles, and logistics transport costs run in a single automated loop.",
    agentDiseaseTitle: "Disease Agent",
    agentMarketTitle: "Market Agent",
    agentBuyerTitle: "Buyer Agent",
    agentProfitTitle: "Profit Agent",
    agentFinalReportTitle: "Final Report",
    uploadCropImage: "Upload Crop Leaf Photo",
    diseaseAnalysisHeader: "Pathology Diagnosis",
    diseaseNameLabel: "Identified Disease",
    confidenceLabel: "Confidence Score",
    severityLabel: "Severity Level",
    marketIntelligenceHeader: "Market Forecasting",
    currentPriceLabel: "Current Mandi Rate",
    predictedPriceLabel: "7-Day Projected Rate",
    trendLabel: "Price Trend Vector",
    buyerRecommendationHeader: "Best Buyer Match",
    bestBuyerLabel: "Matched Dealer",
    buyerRatingLabel: "Dealer Rating Star",
    offeredPriceLabel: "Dealer Offer Bid",
    profitCalculatorHeader: "Net Profit Calculator",
    expectedRevenueLabel: "Expected Gross Revenue",
    transportCostLabel: "Freight Logistics Cost",
    expectedProfitLabel: "Expected Net Profit",
    finalRecommendationHeader: "AI Command Recommendation",
    commandCenterHistory: "Consolidated AI Command History",
    commandCenterHistoryEmpty: "No previous Command Center reports found."
  },
  hi: {
    appName: "एग्रो-लिंक (AGRO-LINK)",
    tagline: "एआई-संचालित स्मार्ट कृषि बाज़ार",
    navHome: "डैशबोर्ड",
    navMarketplace: "बाज़ार",
    navAiHub: "एआई हब",
    navChat: "बोलियां और चैट",
    navLogout: "लॉगआउट",
    
    authTitle: "एग्रो-लिंक में आपका स्वागत है",
    authLogin: "लॉगिन करें",
    authRegister: "पंजीकरण करें",
    authRole: "अपनी भूमिका चुनें",
    roleFarmer: "किसान (फसल विक्रेता)",
    roleDealer: "डीलर (फसल खरीदार)",
    roleShopkeeper: "दुकानदार (उर्वरक विक्रेता)",
    authEmail: "ईमेल पता",
    authPassword: "पासवर्ड",
    authName: "पूरा नाम",
    authPhone: "फ़ोन नंबर",
    authAddress: "खेत/दुकान का पता",
    authNoAccount: "खाता नहीं है? पंजीकरण करें",
    authHaveAccount: "पहले से ही खाता है? लॉगिन करें",
    authSuccess: "सफलतापूर्वक प्रमाणित!",
    authError: "प्रमाणीकरण विफल रहा। कृपया पुनः प्रयास करें।",

    dashTitle: "कृषि खुफिया डैशबोर्ड",
    iotHeader: "आईओटी (IoT) मिट्टी की निगरानी",
    moisture: "मिट्टी की नमी",
    temperature: "तापमान",
    soilPh: "मिट्टी का पीएच",
    iotAlertOk: "मिट्टी का स्वास्थ्य अनुकूल है",
    iotAlertDanger: "चेतावनी: नमी सीमा से नीचे! सिंचाई की सलाह दी जाती है।",
    weatherHeader: "वास्तविक समय मौसम और सलाह",
    weatherHumidity: "आर्द्रता",
    weatherWind: "हवा की गति",
    weatherAdvisory: "कृषि संबंधी सलाह",
    weatherAdviseFine: "साफ आसमान। फसल कटाई और उर्वरक छिड़काव के लिए उत्कृष्ट परिस्थितियां।",
    weatherAdviseRain: "बारिश की उम्मीद है। उर्वरक डालना स्थगित करें। जल निकासी की जाँच करें।",
    voiceAssistant: "आवाज सहायक सक्रिय",
    voiceInstruction: "आदेश सुनने के लिए 'help' बोलें। 'AI hub पर जाएं', 'कीमत जांचें' बोलकर प्रयास करें।",

    marketTitle: "विकेंद्रीकृत कृषि बाज़ार",
    marketCropCatalog: "ताजा किसान उपज",
    marketShopCatalog: "उर्वरक और कीटनाशक स्टोर",
    marketUploadProduce: "उपज सूची अपलोड करें",
    marketUploadProduct: "उर्वरक/कीटनाशक उत्पाद सूचीबद्ध करें",
    marketCropName: "फसल का नाम",
    marketCategory: "श्रेणी",
    marketQuantity: "मात्रा (किलोग्राम)",
    marketPrice: "मूल्य (प्रति किलोग्राम)",
    marketDesc: "विवरण और ग्रेड",
    marketUploadBtn: "सूची अपलोड करें",
    nearbyShops: "आसपास के अनुशंसित दुकानदार (50 किमी के भीतर)",
    nearbyDistance: "दूरी",
    nearbyBuy: "दुकान पर जाएं",
    makeOfferBtn: "बोली लगाएं / मोलभाव करें",
    buyNowBtn: "सीधे खरीदें",
    orderPlaced: "ऑर्डर अनुरोध सफलतापूर्वक बनाया गया!",
    aiListingHeader: "एआई ऑटो-लिस्टिंग सहायक",
    aiListingDesc: "अपनी उपज का एक फोटो अपलोड करें। एग्रो-लिंक एआई स्वचालित रूप से फसल, गुणवत्ता ग्रेड और अनुशंसित मूल्य का पता लगा लेगा।",
    aiScanning: "एआई फसल की विशेषताओं को स्कैन कर रहा है...",
    aiSuggestedPrice: "अनुशंसित मूल्य",
    aiDetectedGrade: "ग्रेड",
    aiDetectedQuality: "गुणवत्ता",
    aiVerifiedBadge: "एआई सत्यापित",

    aiHubTitle: "स्मार्ट कृषि एआई सेवाएं",
    aiDiseaseDetect: "एआई पत्ती रोग डिटेक्टर",
    aiUploadLeaf: "रोगों की पहचान करने और उपचार प्राप्त करने के लिए फसल की पत्ती का फोटो अपलोड करें।",
    aiDropzone: "पत्ती का फोटो यहां क्लिक करें या खींचें",
    aiDetecting: "एआई पत्ती के पैटर्न का विश्लेषण कर रहा है...",
    aiCure: "अनुशंसित उपचार और दवाएं",
    aiPricePredict: "फसल मूल्य रुझान भविष्यवक्ता",
    aiSelectCrop: "फसल श्रेणी चुनें",
    aiSelectState: "राज्य चुनें",
    aiPredictBtn: "मूल्य रुझान का अनुमान लगाएं",
    aiPriceResult: "अगले महीने के लिए अनुमानित मूल्य",
    aiTrend: "बाज़ार रुझान स्थिति",
    aiSoilRecommend: "एनपीके (NPK) स्मार्ट मृदा सलाहकार",
    aiEnterNutrients: "मिट्टी के एन-पी-के (N-P-K) मान दर्ज करें (ppm)",
    aiCheckSoil: "मिट्टी के स्वास्थ्य का विश्लेषण करें",
    aiSoilStatus: "मिट्टी पोषक तत्व की स्थिति",
    aiRecommendedFertilizer: "सर्वोत्तम अनुशंसित उर्वरक",
    aiSoilDosage: "लक्षित खुराक",

    chatTitle: "लाइव बोली बातचीत कक्ष",
    chatActiveOffer: "वर्तमान प्रस्तावित बोली मूल्य",
    chatAcceptBtn: "सौदा स्वीकार करें",
    chatRejectBtn: "अस्वीकार और रीसेट",
    chatPlaceBid: "अपनी बातचीत की पेशकश दर्ज करें (₹/किग्रा)",
    chatSendBtn: "बोली भेजें",
    navCopilot: "एआई कोपायलट",
    copilotChatTitle: "एआई किसान कोपायलट",
    copilotStatusOnline: "ऑनलाइन (कृषि विशेषज्ञ)",
    copilotPlaceholder: "मुझसे फसलों, मिट्टी, पानी के बारे में कुछ भी पूछें...",
    copilotClearBtn: "वार्तालाप मिटाएं",
    copilotVoiceActive: "आवाज सक्रिय",
    copilotSpeakBtn: "बोलें",
    copilotListening: "सुन रहा है...",
    copilotToggleSpeech: "आवाज आउटपुट",
    copilotSuggestLeaves: "मेरी पत्तियां पीली क्यों हो रही हैं?",
    copilotSuggestFertilizer: "कौन सा उर्वरक उपयोग करें?",
    copilotSuggestWater: "सिंचाई के लिए कितना पानी चाहिए?",
    copilotSuggestCrop: "अगले सीजन के लिए सबसे अच्छी फसल?",
    copilotSoilMetrics: "सॉइल टेलीमेट्री संदर्भ सिमुलेट करें",
    copilotSoilMetricsDesc: "व्यक्तिगत समाधानों के लिए एआई कोपायलट को लाइव आईओटी रीडिंग भेजें",
    copilotMoistureLabel: "मिट्टी की नमी",
    copilotPhLabel: "मिट्टी का पीएच",
    copilotTempLabel: "तापमान",
    copilotTelemetryCheckbox: "एआई को टेलीमेट्री भेजें",
    copilotOpenFullPage: "पूरा पेज खोलें",
    
    // Price Predictor
    navPricePredictor: "मूल्य भविष्यवक्ता",
    pricePredictorTitle: "एआई फसल मूल्य पूर्वानुमान प्रणाली",
    pricePredictorDesc: "मशीन लर्निंग ट्रेंड मॉडल के आधार पर कल, 3-दिन, 7-दिन और 15-दिन की कीमतों का अनुमान लगाने के लिए अपनी फसल का विवरण दर्ज करें।",
    priceSelectCrop: "फसल का नाम",
    priceSelectLocation: "स्थान (राज्य)",
    priceEnterQuantity: "मात्रा (किलोग्राम में)",
    pricePredictSubmit: "पूर्वानुमान लगाएं",
    priceTomorrow: "कल की कीमत",
    priceThreeDay: "3-दिन की कीमत",
    priceSevenDay: "7-दिन की कीमत",
    priceFifteenDay: "15-दिन की कीमत",
    priceCurrent: "वर्तमान बाजार मूल्य",
    priceRecommendAction: "एआई अनुशंसा",
    priceSavePrediction: "इस पूर्वानुमान को सहेजें",
    pricePredictionHistory: "पूर्वानुमान इतिहास",
    priceHistoryDelete: "हटाएं",
    priceHistoryEmpty: "कोई सहेजा गया पूर्वानुमान नहीं मिला।",

    // Negotiation Assistant
    navNegotiationAssistant: "मोलभाव सहायक",
    negotiationAssistantTitle: "एआई मोलभाव सहायक",
    negotiationAssistantDesc: "सौदा निष्पक्षता, अपेक्षित लाभ, जोखिम प्रोफाइल और काउंटर-ऑफ़र लक्ष्यों को सत्यापित करने के लिए वर्तमान बाजार मूल्यों की तुलना में डीलर बोली ऑफ़र का मूल्यांकन करें।",
    negSelectCrop: "फसल चुनें",
    negOfferedPrice: "डीलर प्रस्तावित मूल्य (प्रति किग्रा)",
    negMarketPrice: "वर्तमान बाजार मूल्य (प्रति किग्रा)",
    negQuantity: "फसल की मात्रा (किग्रा)",
    negLocation: "खेत का स्थान (राज्य)",
    negSubmitBtn: "प्रस्ताव निष्पक्षता का विश्लेषण करें",
    negDifference: "मूल्य अंतर",
    negExpectedProfit: "अपेक्षित कुल लाभ",
    negProfitDiff: "बाजार बनाम लाभ/हानि",
    negRiskLevel: "जोखिम रेटिंग",
    negFairnessScore: "निष्पक्षता स्कोर",
    negNegotiationScore: "मोलभाव करने की क्षमता",
    negCounterOffer: "सुझाया गया काउंटर ऑफर",
    negHistoryEmpty: "कोई सहेजा गया मोलभाव विश्लेषण नहीं मिला।",

    // Buyer Matching
    navBuyerMatching: "खरीदार मिलान",
    buyerMatchingTitle: "एआई स्मार्ट खरीदार मिलान",
    buyerMatchingDesc: "कीमत, दूरी, विश्वास सूचकांक और लेनदेन के इतिहास के आधार पर अपनी फसल के लिए सर्वोत्तम पंजीकृत डीलरों की पहचान करें और उन्हें रैंक करें।",
    matchEnterQty: "फसल की मात्रा (किलोग्राम में)",
    matchSubmitBtn: "सर्वोत्तम खरीदार खोजें",
    matchHistoryTitle: "सहेजे गए खरीदार मिलान इतिहास",
    matchHistoryEmpty: "कोई सहेजा गया खरीदार मिलान इतिहास नहीं मिला।",
    matchDealerName: "डीलर का नाम",
    matchDistance: "दूरी",
    matchPrice: "प्रस्तावित मूल्य",
    matchTrustScore: "विश्वास स्कोर",
    matchRating: "रेटिंग",
    matchTransactions: "लेन-देनों",
    matchScore: "मैच स्कोर",
    bestProfitBadge: "सर्वोत्तम लाभ",
    fastestSaleBadge: "सबसे तेज़ बिक्री",
    connectDealerBtn: "सौदा मोलभाव करें",
    saveMatchSnapshot: "मिलान स्नैपशॉट सहेजें",
    
    // Crop Health
    navCropHealth: "फसल स्वास्थ्य",
    cropHealthTitle: "एआई फसल स्वास्थ्य और रोग प्रबंधन",
    cropHealthDesc: "अपनी फसल की पत्ती का फोटो अपलोड करें और तुरंत नैदानिक पहचान, गंभीरता मूल्यांकन, कस्टम उपचार दिशानिर्देश, रासायनिक उर्वरक अनुशंसा और दुकानदार मूल्य प्राप्त करें।",
    healthAnalyzeBtn: "फसल स्वास्थ्य का विश्लेषण करें",
    healthAnalyzing: "एआई पत्ती विसंगतियों का निदान कर रहा है...",
    healthReportTitle: "फसल स्वास्थ्य निदान रिपोर्ट",
    healthHistoryTitle: "फसल स्वास्थ्य स्कैन इतिहास और रुझान",
    healthHistoryEmpty: "कोई पुराना फसल स्कैन नहीं मिला।",
    symptomsLabel: "लक्षणों की पहचान की गई",
    treatmentLabel: "निर्धारित उपचार",
    costLabel: "अनुमानित उपचार लागत",
    fertilizersLabel: "अनुशंसित उर्वरक",
    pesticidesLabel: "अनुशंसित कीटनाशक",
    nearbyShopsLabel: "अनुशंसित उत्पाद बेचने वाली नजदीकी दुकानें",
    buyNowInputBtn: "अभी खरीदें",
    printReportBtn: "स्वास्थ्य रिपोर्ट प्रिंट करें",
    severityBadge: "गंभीरता",
    confidenceBadge: "आत्मविश्वास",
    scanDate: "स्कैन तिथि",
    totalScans: "कुल स्कैन की संख्या",
    highSeverityAlerts: "उच्च गंभीरता अलर्ट",
    healthyScansRatio: "स्वस्थ फसल दर",
    diseaseTrendChart: "रोगों का वितरण",
    severityTrendChart: "फसल स्वास्थ्य गंभीरता समयरेखा",
    weatherAdvisorTitle: "एआई मौसम सलाहकार और परामर्श",
    weatherAdvisorDesc: "एआई विशेषज्ञ फसल निर्धारण सलाह के साथ लाइव ओपन-मेटो स्थानीय पूर्वानुमान।",
    irrigationAdvisor: "सिंचाई संबंधी सलाह",
    fertilizerAdvisor: "उर्वरक संबंधी सलाह",
    pestAdvisor: "कीट एवं रोग जोखिम",
    weeklyForecast: "7-दिवसीय मौसम पूर्वानुमान",
    weatherCheckHistory: "मौसम जांच इतिहास",
    weatherTempTrend: "स्थानीय तापमान पूर्वानुमान रुझान",
    weatherRainTrend: "7-दिवसीय दैनिक वर्षा संभावना चार्ट",
    weatherCheckBtn: "मौसम टेलीमेट्री ताज़ा करें",
    weatherChecking: "लाइव ओपन-मेटो फ़ीड्स प्राप्त किए जा रहे हैं...",
    navAgentSystem: "एजेंट प्रणाली",
    agentSystemTitle: "एआई मल्टी-एजेंट कृषि प्रणाली",
    agentSystemDesc: "बीमारी का निदान करने, मूल्य निर्धारण का अनुमान लगाने, खरीदार डीलरों का मिलान करने और माल ढुलाई रसद की योजना बनाने के लिए क्रमिक रूप से चलने वाले 4 विशेष एआई एजेंटों को निष्पादित करें।",
    diseaseAgentLabel: "एजेंट 1: पत्ती रोग विशेषज्ञ",
    marketAgentLabel: "एजेंट 2: मूल्य पूर्वानुमान विशेषज्ञ",
    buyerAgentLabel: "एजेंट 3: खरीदार मिलान दलाल",
    logisticsAgentLabel: "एजेंट 4: रसद और परिवहन विशेषज्ञ",
    agentRunBtn: "एजेंट पाइपलाइन शुरू करें",
    agentRunning: "एआई एजेंट पाइपलाइन चल रही है...",
    workflowProgress: "मल्टी-एजेंट कार्यप्रवाह प्रगति",
    agentConsoleLogs: "एजेंट पाइपलाइन टर्मिनल फीड",
    finalReportTitle: "एकीकृत कृषि वाणिज्य रिपोर्ट",
    netEarningsLabel: "शुद्ध अनुमानित आय",
    freightCostLabel: "माल ढुलाई परिवहन लागत",
    logisticsMapLabel: "इष्टतम माल ढुलाई मार्ग नक्शा",
    workflowHistory: "मल्टी-एजेंट रन इतिहास",
    fieldHandbookTitle: "किसान गाइड और शब्दावली",
    moistureHandbookTitle: "मिट्टी की नमी (जल सामग्री)",
    moistureHandbookDesc: "यह मिट्टी में पानी के प्रतिशत को दर्शाता है। फसलों (गेहूं, टमाटर) के लिए आदर्श स्तर 40-60% है। 30% से कम होने पर तत्काल सिंचाई करने की चेतावनी जारी होती है ताकि फसल सूखे नहीं।",
    phHandbookTitle: "मिट्टी का पीएच (अम्लता/क्षारीयता)",
    phHandbookDesc: "पीएच मिट्टी की अम्लता को मापता है। सर्वोत्तम रेंज 6.0-7.5 (तटस्थ) है। बहुत कम पीएच में पोषक तत्व अवशोषित नहीं होते; मिट्टी में सुधार के लिए कृषि चूना डालें।",
    tempHandbookTitle: "तापमान (उष्मा सूचकांक)",
    tempHandbookDesc: "फसल के बढ़ने के लिए 25-32°C तापमान सबसे अच्छा है। अधिक तापमान से मिट्टी का पानी जल्दी भाप बनकर उड़ जाता है, इसलिए जल्दी सिंचाई करें।",
    sporeHandbookTitle: "फंगल बीजाणु (Spore) जोखिम सूचकांक",
    sporeHandbookDesc: "एआई हवा की नमी के आधार पर फंगस रोग के खतरे की गणना करता है। सुरक्षित: 0-45%। चेतावनी: 45-75% (नीम तेल का छिड़काव करें)। खतरा: >75% (24 घंटे में कॉपर ऑक्सीक्लोराइड का छिड़काव करें)।",
    agentWorkflowGuideTitle: "एग्रो-लिंक मल्टी-एजेंट गाइड",
    agentWorkflowGuideDesc: "यह प्रणाली 4 विशेषज्ञ एआई एजेंटों को एक साथ चलाकर रोग निदान, मूल्य निर्धारण, खरीदार और परिवहन की स्वचालित व्यवस्था करती है।",
    agent1GuideTitle: "एजेंट 1: पत्ती रोग विशेषज्ञ",
    agent1GuideDesc: "अपलोड की गई पत्ती की तस्वीर से रोग (जैसे रस्ट या ब्लाइट) की पहचान करता है, उसकी गंभीरता मापता है और सटीक इलाज व खर्च बताता है।",
    agent2GuideTitle: "एजेंट 2: मूल्य पूर्वानुमान विशेषज्ञ",
    agent2GuideDesc: "मंडी के ऐतिहासिक मूल्य डेटा के आधार पर आगामी कीमतों का अनुमान लगाता है और बताता है कि फसल 'रोकनी' (Hold) चाहिए या तुरंत 'बेचनी' (Sell) चाहिए।",
    agent3GuideTitle: "एजेंट 3: खरीदार मिलान दलाल",
    agent3GuideDesc: "फसल मात्रा के आधार पर खरीदार डीलरों के मूल्य प्रस्ताव, ट्रस्ट स्कोर और रेटिंग का विश्लेषण करके आपको सबसे अधिक लाभ देने वाले डीलर से मिलाता है।",
    agent4GuideTitle: "एजेंट 4: रसद और परिवहन विशेषज्ञ",
    agent4GuideDesc: "परिवहन दूरी, समय और किराए की गणना करता है और खरीदार की बोली से किराया घटाकर आपको मिलने वाली शुद्ध आय (Net Profit) का अनुमान लगाता है।",
    navAiCommandCenter: "एआई कमांड सेंटर",
    aiCommandCenterTitle: "एआई कमांड सेंटर और निदान कक्ष",
    aiCommandCenterDesc: "एक एकीकृत संचालन डेस्क जहां फसल रोग विश्लेषण, मूल्य पूर्वानुमान, निकटतम खरीदार बोली और परिवहन रसद किराया एक साथ स्वचालित रूप से चलते हैं।",
    agentDiseaseTitle: "रोग एजेंट",
    agentMarketTitle: "बाजार एजेंट",
    agentBuyerTitle: "खरीदार एजेंट",
    agentProfitTitle: "लाभ एजेंट",
    agentFinalReportTitle: "अंतिम रिपोर्ट",
    uploadCropImage: "फसल पत्ती फोटो अपलोड करें",
    diseaseAnalysisHeader: "रोग निदान विश्लेषण",
    diseaseNameLabel: "पहचाना गया रोग",
    confidenceLabel: "सटीकता दर",
    severityLabel: "गंभीरता स्तर",
    marketIntelligenceHeader: "बाजार पूर्वानुमान",
    currentPriceLabel: "वर्तमान मंडी दर",
    predictedPriceLabel: "7-दिवसीय अनुमानित दर",
    trendLabel: "मूल्य का रुख (Trend)",
    buyerRecommendationHeader: "सर्वोत्तम खरीदार मिलान",
    bestBuyerLabel: "चयनित डीलर",
    buyerRatingLabel: "डीलर रेटिंग स्टार",
    offeredPriceLabel: "डीलर प्रस्तावित बोली",
    profitCalculatorHeader: "शुद्ध लाभ कैलकुलेटर",
    expectedRevenueLabel: "अपेक्षित सकल राजस्व",
    transportCostLabel: "भाड़ा परिवहन खर्च",
    expectedProfitLabel: "अपेक्षित शुद्ध लाभ",
    finalRecommendationHeader: "एआई कमांड सिफारिश",
    commandCenterHistory: "एकीकृत कमांड सेंटर इतिहास",
    commandCenterHistoryEmpty: "कोई पुराना कमांड सेंटर रिपोर्ट नहीं मिला।"
  },
  mr: {
    appName: "अ‍ॅग्रो-लिंक (AGRO-LINK)",
    tagline: "एआय-संचालित स्मार्ट कृषी बाजारपेठ",
    navHome: "डॅशबोर्ड",
    navMarketplace: "बाजारपेठ",
    navAiHub: "एआय हब",
    navChat: "बोली आणि चॅट",
    navLogout: "लॉगआउट",
    
    authTitle: "अ‍ॅग्रो-लिंकमध्ये आपले स्वागत आहे",
    authLogin: "लॉगिन करा",
    authRegister: "नोंदणी करा",
    authRole: "तुमची भूमिका निवडा",
    roleFarmer: "शेतकरी (पीक विक्रेता)",
    roleDealer: "डीलर (पीक खरेदीदार)",
    roleShopkeeper: "दुकानदार (खत विक्रेता)",
    authEmail: "ईमेल पत्ता",
    authPassword: "पासवर्ड",
    authName: "पूर्ण नाव",
    authPhone: "फोन नंबर",
    authAddress: "शेत/दुकानाचा पत्ता",
    authNoAccount: "खाते नाही? नोंदणी करा",
    authHaveAccount: "आधीच खाते आहे? लॉगिन करा",
    authSuccess: "यशस्वीरित्या प्रमाणित!",
    authError: "प्रमाणीकरण अयशस्वी. कृपया पुन्हा प्रयत्न करा.",

    dashTitle: "कृषी बुद्धिमत्ता डॅशबोर्ड",
    iotHeader: "आयओटी (IoT) मातीची देखरेख",
    moisture: "मातीची आर्द्रता",
    temperature: "तापमान",
    soilPh: "मातीचे पीएच (pH)",
    iotAlertOk: "मातीचे आरोग्य अनुकूल आहे",
    iotAlertDanger: "धोका: आर्द्रता मर्यादेपेक्षा कमी! सिंचनाची शिफारस केली जाते.",
    weatherHeader: "रिअल-टाइम हवामान आणि सल्ला",
    weatherHumidity: "आर्द्रता",
    weatherWind: "वाऱ्याचा वेग",
    weatherAdvisory: "कृषी सल्ला",
    weatherAdviseFine: "स्वच्छ आकाश. पीक काढणी आणि खत फवारणीसाठी उत्तम परिस्थिती.",
    weatherAdviseRain: "पावसाची शक्यता. खत वापरणे पुढे ढकला. पाण्याचा निचरा तपासा.",
    voiceAssistant: "व्हॉइस असिस्टंट सक्रिय",
    voiceInstruction: "आदेश ऐकण्यासाठी 'help' बोला. 'AI hub वर जा', 'किंमत तपासा' बोलून पहा.",

    marketTitle: "विकेंद्रित कृषी बाजारपेठ",
    marketCropCatalog: "ताजा शेतकरी माल",
    marketShopCatalog: "खते आणि कीटकनाशके स्टोअर",
    marketUploadProduce: "माल अपलोड करा",
    marketUploadProduct: "खते/कीटकनाशके उत्पादन सूचीबद्ध करा",
    marketCropName: "पिकाचे नाव",
    marketCategory: "श्रेणी",
    marketQuantity: "प्रमाण (किलो)",
    marketPrice: "किंमत (प्रति किलो)",
    marketDesc: "वर्णन आणि ग्रेड",
    marketUploadBtn: "सूची अपलोड करा",
    nearbyShops: "जवळपासचे शिफारस केलेले दुकानदार (५० किमीच्या आत)",
    nearbyDistance: "अंतर",
    nearbyBuy: "दुकानाला भेट द्या",
    makeOfferBtn: "बोली लावा / बोलणी करा",
    buyNowBtn: "थेट खरेदी करा",
    orderPlaced: "ऑर्डरची विनंती यशस्वीरित्या तयार केली गेली!",
    aiListingHeader: "एआय ऑटो-लिस्टिंग सहाय्यक",
    aiListingDesc: "तुमच्या पिकाचा एक फोटो अपलोड करा. अ‍ॅग्रो-लिंक एआय पीक, गुणवत्ता ग्रेड आणि शिफारस केलेली किंमत स्वयंचलितपणे शोधून काढेल.",
    aiScanning: "एआय पिकाची वैशिष्ट्ये स्कॅन करत आहे...",
    aiSuggestedPrice: "शिफारस केलेली किंमत",
    aiDetectedGrade: "ग्रेड",
    aiDetectedQuality: "गुणवत्ता",
    aiVerifiedBadge: "एआय सत्यापित",

    aiHubTitle: "स्मार्ट कृषी एआय सेवा",
    aiDiseaseDetect: "एआय पाने रोग शोधक",
    aiUploadLeaf: "रोगांची ओळख पटवण्यासाठी आणि उपाय मिळवण्यासाठी पिकाच्या पाण्याचा फोटो अपलोड करा.",
    aiDropzone: "पानाचा फोटो येथे क्लिक करा किंवा ड्रॅग करा",
    aiDetecting: "एआय पानांच्या नमुन्यांचे विश्लेषण करत आहे...",
    aiCure: "शिफारस केलेले उपाय आणि औषधे",
    aiPricePredict: "पीक किंमत ट्रेंड प्रेडिक्टर",
    aiSelectCrop: "पीक श्रेणी निवडा",
    aiSelectState: "राज्य निवडा",
    aiPredictBtn: "किंमतीचा अंदाज लावा",
    aiPriceResult: "पुढील महिन्यासाठी अंदाजित किंमत",
    aiTrend: "बाजार ट्रेंड स्थिती",
    aiSoilRecommend: "एनपीके (NPK) स्मार्ट मृदा सल्लागार",
    aiEnterNutrients: "मातीचे एन-पी-के (N-P-K) मूल्य प्रविष्ट करा (ppm)",
    aiCheckSoil: "मातीचे आरोग्य तपासा",
    aiSoilStatus: "मातीतील पोषक तत्वांची स्थिती",
    aiRecommendedFertilizer: "उत्तम शिफारस केलेले खत",
    aiSoilDosage: "लक्ष्यित डोस",

    chatTitle: "थेट बोली चर्चा कक्ष",
    chatActiveOffer: "सध्याची प्रस्तावित बोली किंमत",
    chatAcceptBtn: "सौदा मंजूर करा",
    chatRejectBtn: "नकार द्या आणि रीसेट करा",
    chatPlaceBid: "तुमची बोली किंमत प्रविष्ट करा (₹/किलो)",
    chatSendBtn: "बोली पाठवा",
    navCopilot: "एआय कोपायलट",
    copilotChatTitle: "एआय शेतकरी कोपायलट",
    copilotStatusOnline: "ऑनलाइन (कृषी तज्ज्ञ)",
    copilotPlaceholder: "मला पिके, माती, पाण्याबद्दल काहीही विचारा...",
    copilotClearBtn: "चर्चा पुसून टाका",
    copilotVoiceActive: "आवाज सक्रिय",
    copilotSpeakBtn: "बोला",
    copilotListening: "ऐकत आहे...",
    copilotToggleSpeech: "व्हॉइस आउटपुट",
    copilotSuggestLeaves: "माझी पाने पिवळी का पडत आहेत?",
    copilotSuggestFertilizer: "कोणते खत वापरावे?",
    copilotSuggestWater: "पिकाला किती पाणी द्यावे?",
    copilotSuggestCrop: "पुढील हंगामासाठी सर्वोत्तम पीक कोणते?",
    copilotSoilMetrics: "मातीचे मोजमाप संदर्भ सिम्युलेट करा",
    copilotSoilMetricsDesc: "वैयक्तिकृत उपायांसाठी एआय कोपायलटला थेट आयओटी रीडिंग पाठवा",
    copilotMoistureLabel: "मातीची आर्द्रता",
    copilotPhLabel: "मातीचे पीएच",
    copilotTempLabel: "तापमान",
    copilotTelemetryCheckbox: "एआय ला टेलीमेट्री पाठवा",
    copilotOpenFullPage: "पूर्ण पृष्ठ उघडा",
    
    // Price Predictor
    navPricePredictor: "किंमत प्रेडिक्टर",
    pricePredictorTitle: "एआय पीक किंमत अंदाज प्रणाली",
    pricePredictorDesc: "मशीन लर्निंग ट्रेंड मॉडेलच्या आधारे उद्याच्या, ३-दिवस, ७-दिवस आणि १५-दिवसांच्या किंमतींचा अंदाज घेण्यासाठी आपल्या पिकाचा तपशील प्रविष्ट करा.",
    priceSelectCrop: "पिकाचे नाव",
    priceSelectLocation: "स्थान (राज्य)",
    priceEnterQuantity: "प्रमाण (किलोमध्ये)",
    pricePredictSubmit: "अंदाज लावा",
    priceTomorrow: "उद्याची किंमत",
    priceThreeDay: "३-दिवसांची किंमत",
    priceSevenDay: "७-दिवसांची किंमत",
    priceFifteenDay: "१५-दिवसांची किंमत",
    priceCurrent: "सध्याची बाजार किंमत",
    priceRecommendAction: "एआय शिफारस",
    priceSavePrediction: "हा अंदाज जतन करा",
    pricePredictionHistory: "अंदाज इतिहास",
    priceHistoryDelete: "काढून टाका",
    priceHistoryEmpty: "कोणतेही जतन केलेले अंदाज आढळले नाहीत.",

    // Negotiation Assistant
    navNegotiationAssistant: "तडजोड सहाय्यक",
    negotiationAssistantTitle: "एआय तडजोड सहाय्यक",
    negotiationAssistantDesc: "सौदा निष्पक्षता, अपेक्षित नफा, जोखीम प्रोफाइल आणि काउंटर-ऑफर उद्दिष्टे सत्यापित करण्यासाठी सध्याच्या बाजार मूल्यांच्या तुलनेत डीलर बोली ऑफरचे मूल्यांकन करा.",
    negSelectCrop: "पीक निवडा",
    negOfferedPrice: "डीलर प्रस्तावित किंमत (प्रति किलो)",
    negMarketPrice: "सध्याची बाजार किंमत (प्रति किलो)",
    negQuantity: "पिकाचे प्रमाण (किलो)",
    negLocation: "शेताचे ठिकाण (राज्य)",
    negSubmitBtn: "ऑफरच्या निष्पक्षतेचे विश्लेषण करा",
    negDifference: "किंमतीतील फरक",
    negExpectedProfit: "अपेक्षित एकूण नफा",
    negProfitDiff: "बाजार विरुद्ध नफा/तोटा",
    negRiskLevel: "जोखीम रेटिंग",
    negFairnessScore: "निष्पक्षता स्कोअर",
    negNegotiationScore: "घासाघिस करण्याची क्षमता",
    negCounterOffer: "सुचविलेली काउंटर ऑफर",
    negHistoryEmpty: "कोणतेही जतन केलेले तडजोड विश्लेषण आढळले नाही.",

    // Buyer Matching
    navBuyerMatching: "खरेदीदार जुळणी",
    buyerMatchingTitle: "एआय स्मार्ट खरेदीदार जुळणी",
    buyerMatchingDesc: "किंमत, अंतर, विश्वास निर्देशांक आणि व्यवहारांच्या इतिहासाच्या आधारे आपल्या पिकासाठी सर्वोत्तम नोंदणीकृत डीलर्स ओळखा आणि त्यांना रँक करा.",
    matchEnterQty: "पिकाचे प्रमाण (किलोमध्ये)",
    matchSubmitBtn: "उत्तम खरेदीदार शोधा",
    matchHistoryTitle: "जतन केलेले खरेदीदार जुळणी इतिहास",
    matchHistoryEmpty: "कोणतेही जतन केलेले खरेदीदार जुळणी इतिहास आढळले नाहीत.",
    matchDealerName: "डीलरचे नाव",
    matchDistance: "अंतर",
    matchPrice: "प्रस्तावित किंमत",
    matchTrustScore: "विश्वास स्कोअर",
    matchRating: "रेटिंग",
    matchTransactions: "व्यवहार",
    matchScore: "मॅच स्कोअर",
    bestProfitBadge: "सर्वोत्तम नफा",
    fastestSaleBadge: "सर्वात वेगवान विक्री",
    connectDealerBtn: "बोली घासाघिस करा",
    saveMatchSnapshot: "जुळणी स्नॅपशॉट जतन करा",
    
    // Crop Health
    navCropHealth: "पीक आरोग्य",
    cropHealthTitle: "एआय पीक आरोग्य आणि रोग व्यवस्थापन",
    cropHealthDesc: "त्वरित निदान, तीव्रतेचे मूल्यांकन, सानुकूल उपचार मार्गदर्शक तत्त्वे, खत आणि औषधांची शिफारस आणि दुकानदार किंमती मिळवण्यासाठी पिकाच्या पाण्याचा फोटो अपलोड करा.",
    healthAnalyzeBtn: "पीक आरोग्याचे विश्लेषण करा",
    healthAnalyzing: "एआय पानांच्या विसंगतींचे निदान करत आहे...",
    healthReportTitle: "पीक आरोग्य निदान अहवाल",
    healthHistoryTitle: "पीक आरोग्य स्कॅन इतिहास आणि ट्रेंड",
    healthHistoryEmpty: "कोणतेही जुने पीक स्कॅन आढळले नाहीत.",
    symptomsLabel: "लक्षणे आढळली",
    treatmentLabel: "नियोजित उपचार",
    costLabel: "अंदाजे उपचार खर्च",
    fertilizersLabel: "शिफारस केलेले खत",
    pesticidesLabel: "शिफारस केलेले कीटकनाशक",
    nearbyShopsLabel: "जवळपासची दुकाने (शिफारस केलेली उत्पादने)",
    buyNowInputBtn: "आता खरेदी करा",
    printReportBtn: "आरोग्य अहवाल प्रिंट करा",
    severityBadge: "तीव्रता",
    confidenceBadge: "विश्वास",
    scanDate: "स्कॅन तारीख",
    totalScans: "एकूण स्कॅन्स",
    highSeverityAlerts: "उच्च तीव्रता अलर्ट",
    healthyScansRatio: "निरोगी पीक दर",
    diseaseTrendChart: "रोगांचे वितरण",
    severityTrendChart: "पीक आरोग्य तीव्रता टाइमलाइन",
    weatherAdvisorTitle: "एआय हवामान सल्लागार आणि सल्ला",
    weatherAdvisorDesc: "एआय तज्ज्ञ पीक वेळापत्रक सल्ल्यासह थेट ओपन-मेटो स्थानिक अंदाज.",
    irrigationAdvisor: "सिंचन सल्ला",
    fertilizerAdvisor: "खत वापर सल्ला",
    pestAdvisor: "कीड आणि रोग जोखीम",
    weeklyForecast: "७-दिवसीय हवामान अंदाज",
    weatherCheckHistory: "हवामान तपासणी इतिहास",
    weatherTempTrend: "स्थानिक तापमान अंदाज कल",
    weatherRainTrend: "७-दिवसीय दैनिक पाऊस शक्यता चार्ट",
    weatherCheckBtn: "हवामान डेटा ताजे करा",
    weatherChecking: "थेट ओपन-मेटो फीड्स मिळवत आहे...",
    navAgentSystem: "एजंट प्रणाली",
    agentSystemTitle: "एआय मल्टी-एजंट कृषी प्रणाली",
    agentSystemDesc: "रोगाचे निदान करणे, किंमतीचे अंदाज लावणे, खरेदीदार डीलर्स जुळवणे आणि माल वाहतूक लॉजिस्टिकची योजना आखणे यासाठी क्रमाने चालणाऱ्या ४ विशेष एआय एजंट्सची अंमलबजावणी करा.",
    diseaseAgentLabel: "एजंट १: पान रोग तज्ज्ञ",
    marketAgentLabel: "एजंट २: किंमत अंदाज तज्ज्ञ",
    buyerAgentLabel: "एजंट ३: खरेदीदार जुळणी दलाल",
    logisticsAgentLabel: "एजंट ४: लॉजिस्टिक्स आणि ट्रान्सपोर्ट तज्ज्ञ",
    agentRunBtn: "एजंट पाईपलाईन सुरू करा",
    agentRunning: "एआय एजंट पाईपलाईन सुरू आहे...",
    workflowProgress: "मल्टी-एजंट वर्कफ्लो प्रगती",
    agentConsoleLogs: "एजंट पाईपलाईन टर्मिनल फीड",
    finalReportTitle: "एकीकृत कृषी वाणिज्य अहवाल",
    netEarningsLabel: "निव्वळ अंदाजित उत्पन्न",
    logisticsMapLabel: "ऑप्टिमाइझ केलेला माल वाहतूक मार्ग नकाशा",
    workflowHistory: "मल्टी-एजंट रन इतिहास",
    fieldHandbookTitle: "शेतकरी मार्गदर्शिका आणि संज्ञा स्पष्टीकरण",
    moistureHandbookTitle: "मातीची आर्द्रता (पाण्याचे प्रमाण)",
    moistureHandbookDesc: "हे मातीतील पाण्याचे प्रमाण दर्शवते. पिकांसाठी (गहू, टोमॅटो) योग्य प्रमाण 40-60% आहे. 30% पेक्षा कमी असल्यास पिके सुकू नयेत म्हणून त्वरित पाणी देण्याची चेतावणी मिळते.",
    phHandbookTitle: "मातीचे पीएच (अम्लता/क्षारीयता)",
    phHandbookDesc: "पीएच मातीची आम्लता मोजते. पिकांसाठी योग्य पीएच 6.0-7.5 (उदासीन) आहे. अत्यंत कमी पीएच मुळे पिके पोषक द्रव्ये शोषून घेऊ शकत नाहीत; माती सुधारण्यासाठी चुना वापरावा.",
    tempHandbookTitle: "तापमान (पीक उष्णता निर्देशांक)",
    tempHandbookDesc: "पिकांच्या वाढीसाठी 25-32°C तापमान उत्तम मानले जाते. जास्त तापमानामुळे मातीतील पाणी लवकर वाफ होऊन उडून जाते, म्हणून वारंवार पाणी द्यावे.",
    sporeHandbookTitle: "फंगल बीजाणू (Spore) जोखीम निर्देशांक",
    sporeHandbookDesc: "एआय हवेतील दमटपणा आणि पानावरील ओलावा यावरून फंगस रोगाचा अंदाज लावते. सुरक्षित: 0-45%. चेतावणी: 45-75% (प्रतिबंधात्मक कडुनिंब तेल फवारा). धोका: >७५% (२४ तासांत कॉपर ऑक्सीक्लोराइड फवारा).",
    agentWorkflowGuideTitle: "अॅग्रो-लिंक मल्टी-एजंट मार्गदर्शिका",
    agentWorkflowGuideDesc: "ही प्रणाली 4 तज्ज्ञ एआय एजंट्स एकापाठोपाठ चालवून रोग निदान, पिकांचे मूल्य निर्धारण, खरेदीदार आणि वाहतुकीची स्वयंचलित व्यवस्था करते.",
    agent1GuideTitle: "एजंट १: पान रोग तज्ज्ञ",
    agent1GuideDesc: "अपलोड केलेल्या पानांच्या फोटोवरून रोगाचे (उदा. तांबेरा किंवा करपा) निदान करतो, तीव्रता मोजतो आणि योग्य औषध व खर्च सुचवतो.",
    agent2GuideTitle: "एजंट २: किंमत अंदाज तज्ज्ञ",
    agent2GuideDesc: "बाजार समित्यांच्या ऐतिहासिक दरांच्या आधारे पुढील काळातील भावाचा अंदाज लावतो आणि पीक 'ठेवून द्यावे' (Hold) की 'विकून टाकावे' (Sell) याबद्दल सुचवतो.",
    agent3GuideTitle: "एजंट ३: खरेदीदार जुळणी दलाल",
    agent3GuideDesc: "पिकाच्या प्रमाणानुसार खरेदीदार डीलर्सचे दर, ट्रस्ट स्कोअर आणि रेटिंग तपासून तुम्हाला सर्वात जास्त नफा देणाऱ्या व्यापाऱ्याची निवड करतो.",
    agent4GuideTitle: "एजंट ४: लॉजिस्टिक्स आणि ट्रान्सपोर्ट तज्ज्ञ",
    agent4GuideDesc: "वाहतूक अंतर, वेळ आणि खर्च मोजतो आणि व्यापाऱ्याच्या दरातून वाहतूक खर्च वजा करून तुम्हाला मिळणाऱ्या निव्वळ नफ्याचा (Net Profit) अंदाज देतो।",
    navAiCommandCenter: "एआय कमांड सेंटर",
    aiCommandCenterTitle: "एआय कमांड सेंटर आणि निदान कक्ष",
    aiCommandCenterDesc: "एक एकात्मिक ऑपरेशन्स डेस्क जेथे पीक रोग विश्लेषण, किंमत अंदाज, खरेदीदार जुळणी आणि लॉजिस्टिक्स वाहतूक खर्च एकाच स्वयंचलित लूपमध्ये चालतात.",
    agentDiseaseTitle: "रोग एजंट",
    agentMarketTitle: "बाजार एजंट",
    agentBuyerTitle: "खरेदीदार एजंट",
    agentProfitTitle: "नफा एजंट",
    agentFinalReportTitle: "अंतिम अहवाल",
    uploadCropImage: "पिकाच्या पानाचा फोटो अपलोड करा",
    diseaseAnalysisHeader: "रोग निदान विश्लेषण",
    diseaseNameLabel: "ओळखलेला रोग",
    confidenceLabel: "अचूकता दर",
    severityLabel: "तीव्रता पातळी",
    marketIntelligenceHeader: "बाजार अंदाज",
    currentPriceLabel: "सध्याचा बाजार भाव",
    predictedPriceLabel: "७-दिवसीय अंदाजित भाव",
    trendLabel: "किंमतीचा कल (Trend)",
    buyerRecommendationHeader: "सर्वोत्तम खरेदीदार जुळणी",
    bestBuyerLabel: "निवडलेला डीलर",
    buyerRatingLabel: "डीलर रेटिंग स्टार",
    offeredPriceLabel: "डीलरने दिलेला दर",
    profitCalculatorHeader: "निव्वळ नफा कॅल्क्युलेटर",
    expectedRevenueLabel: "अपेक्षित एकूण महसूल",
    transportCostLabel: "वाहतूक लॉजिस्टिक्स खर्च",
    expectedProfitLabel: "अपेक्षित निव्वळ नफा",
    finalRecommendationHeader: "एआय कमांड शिफारस",
    commandCenterHistory: "एकीकृत कमांड सेंटर इतिहास",
    commandCenterHistoryEmpty: "कोणताही जुना कमांड सेंटर अहवाल आढळला नाही."
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('agrolink_lang') || 'en';
  });

  useEffect(() => {
    localStorage.setItem('agrolink_lang', language);
  }, [language]);

  const t = (key) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
